import { db } from "@db";
import { ingredientVariants } from "@db/schema";

// Comprehensive ingredient seed data
export const ingredientSeedData = [
  // ========== FRUITS ==========
  // Apples
  {
    name: "Fuji Apple",
    ingredientType: "fruit" as const,
    baseIngredient: "apple",
    variantName: "Fuji",
    origin: "Japan / Washington State",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.12",
    currentMarketPrice: "0.12",
    seasonalAvailability: ["fall", "winter", "spring"],
    color: "#f4d0a1",
    description: "Sweet and crisp with honey undertones",
    isActive: true,
  },
  {
    name: "Granny Smith Apple",
    ingredientType: "fruit" as const,
    baseIngredient: "apple",
    variantName: "Granny Smith",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.10",
    currentMarketPrice: "0.10",
    seasonalAvailability: ["fall", "winter"],
    color: "#a4d96c",
    description: "Tart and tangy with bright acidity",
    isActive: true,
  },
  {
    name: "Honeycrisp Apple",
    ingredientType: "fruit" as const,
    baseIngredient: "apple",
    variantName: "Honeycrisp",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.15",
    currentMarketPrice: "0.15",
    seasonalAvailability: ["fall"],
    color: "#f9c5d1",
    description: "Explosively crisp with balanced sweet-tart flavor",
    isActive: true,
  },

  // Oranges
  {
    name: "Valencia Orange",
    ingredientType: "fruit" as const,
    baseIngredient: "orange",
    variantName: "Valencia",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.18",
    currentMarketPrice: "0.18",
    seasonalAvailability: ["spring", "summer"],
    color: "#ff9933",
    description: "Sweet and juicy, perfect for fresh juice",
    isActive: true,
  },
  {
    name: "Blood Orange",
    ingredientType: "fruit" as const,
    baseIngredient: "orange",
    variantName: "Blood Orange",
    origin: "Sicily, Italy",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.25",
    currentMarketPrice: "0.25",
    seasonalAvailability: ["winter", "spring"],
    color: "#c1272d",
    description: "Deep crimson with raspberry notes and citrus tang",
    isActive: true,
  },
  {
    name: "Navel Orange",
    ingredientType: "fruit" as const,
    baseIngredient: "orange",
    variantName: "Navel",
    origin: "Florida",
    isOrganic: false,
    isLocalChicago: false,
    baseCostPerOz: "0.16",
    currentMarketPrice: "0.16",
    seasonalAvailability: ["winter", "spring"],
    color: "#ff8c00",
    description: "Seedless and easy to juice with classic orange flavor",
    isActive: true,
  },

  // Berries
  {
    name: "Organic Strawberry",
    ingredientType: "fruit" as const,
    baseIngredient: "strawberry",
    variantName: "Organic",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.28",
    currentMarketPrice: "0.28",
    seasonalAvailability: ["spring", "summer"],
    color: "#fc5a8d",
    description: "Sweet, aromatic berries with vibrant flavor",
    isActive: true,
  },
  {
    name: "Blueberry",
    ingredientType: "fruit" as const,
    baseIngredient: "blueberry",
    variantName: "Wild",
    origin: "Maine",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.35",
    currentMarketPrice: "0.35",
    seasonalAvailability: ["summer"],
    color: "#4f86f7",
    description: "Small, intense berries packed with antioxidants",
    isActive: true,
  },
  {
    name: "Raspberry",
    ingredientType: "fruit" as const,
    baseIngredient: "raspberry",
    variantName: "Red Raspberry",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.42",
    currentMarketPrice: "0.42",
    seasonalAvailability: ["summer"],
    color: "#e30b5c",
    description: "Delicate, sweet-tart berries with floral notes",
    isActive: true,
  },
  {
    name: "Blackberry",
    ingredientType: "fruit" as const,
    baseIngredient: "blackberry",
    variantName: "Marion",
    origin: "Oregon",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.38",
    currentMarketPrice: "0.38",
    seasonalAvailability: ["summer"],
    color: "#2e0854",
    description: "Rich, earthy berries with complex flavor",
    isActive: true,
  },

  // Tropical Fruits
  {
    name: "Mango",
    ingredientType: "fruit" as const,
    baseIngredient: "mango",
    variantName: "Alphonso",
    origin: "India",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.32",
    currentMarketPrice: "0.32",
    seasonalAvailability: ["spring", "summer"],
    color: "#ffbe0b",
    description: "King of mangoes with buttery, sweet flesh",
    isActive: true,
  },
  {
    name: "Pineapple",
    ingredientType: "fruit" as const,
    baseIngredient: "pineapple",
    variantName: "Golden",
    origin: "Hawaii",
    isOrganic: false,
    isLocalChicago: false,
    baseCostPerOz: "0.20",
    currentMarketPrice: "0.20",
    seasonalAvailability: ["year-round"],
    color: "#ffd700",
    description: "Sweet tropical fruit with bright acidity",
    isActive: true,
  },
  {
    name: "Papaya",
    ingredientType: "fruit" as const,
    baseIngredient: "papaya",
    variantName: "Red Lady",
    origin: "Mexico",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.24",
    currentMarketPrice: "0.24",
    seasonalAvailability: ["year-round"],
    color: "#ff8c69",
    description: "Buttery tropical fruit rich in enzymes",
    isActive: true,
  },
  {
    name: "Dragon Fruit",
    ingredientType: "fruit" as const,
    baseIngredient: "dragon fruit",
    variantName: "Pink Pitaya",
    origin: "Vietnam",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.45",
    currentMarketPrice: "0.45",
    seasonalAvailability: ["summer", "fall"],
    color: "#ff006e",
    description: "Exotic fruit with mild sweetness and stunning color",
    isActive: true,
  },

  // Citrus
  {
    name: "Lemon",
    ingredientType: "fruit" as const,
    baseIngredient: "lemon",
    variantName: "Meyer",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.22",
    currentMarketPrice: "0.22",
    seasonalAvailability: ["winter", "spring"],
    color: "#fff44f",
    description: "Sweeter than regular lemons with floral notes",
    isActive: true,
  },
  {
    name: "Lime",
    ingredientType: "fruit" as const,
    baseIngredient: "lime",
    variantName: "Key Lime",
    origin: "Florida",
    isOrganic: false,
    isLocalChicago: false,
    baseCostPerOz: "0.26",
    currentMarketPrice: "0.26",
    seasonalAvailability: ["year-round"],
    color: "#c7ea46",
    description: "Small, aromatic limes with intense tartness",
    isActive: true,
  },
  {
    name: "Grapefruit",
    ingredientType: "fruit" as const,
    baseIngredient: "grapefruit",
    variantName: "Ruby Red",
    origin: "Texas",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.19",
    currentMarketPrice: "0.19",
    seasonalAvailability: ["winter", "spring"],
    color: "#fb6f92",
    description: "Sweet-tart citrus with vibrant pink flesh",
    isActive: true,
  },

  // Stone Fruits
  {
    name: "Peach",
    ingredientType: "fruit" as const,
    baseIngredient: "peach",
    variantName: "Georgia Belle",
    origin: "Georgia",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.27",
    currentMarketPrice: "0.27",
    seasonalAvailability: ["summer"],
    color: "#ffb07c",
    description: "Juicy white peaches with delicate sweetness",
    isActive: true,
  },
  {
    name: "Watermelon",
    ingredientType: "fruit" as const,
    baseIngredient: "watermelon",
    variantName: "Seedless",
    origin: "Indiana",
    isOrganic: false,
    isLocalChicago: true,
    baseCostPerOz: "0.08",
    currentMarketPrice: "0.08",
    seasonalAvailability: ["summer"],
    color: "#ff6b9d",
    description: "Refreshing and hydrating summer fruit",
    isActive: true,
  },
  {
    name: "Pomegranate",
    ingredientType: "fruit" as const,
    baseIngredient: "pomegranate",
    variantName: "Wonderful",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.52",
    currentMarketPrice: "0.52",
    seasonalAvailability: ["fall", "winter"],
    color: "#b91646",
    description: "Ruby red arils bursting with antioxidants",
    isActive: true,
  },

  // ========== VEGETABLES ==========
  // Carrots
  {
    name: "Orange Carrot",
    ingredientType: "vegetable" as const,
    baseIngredient: "carrot",
    variantName: "Orange",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.09",
    currentMarketPrice: "0.09",
    seasonalAvailability: ["year-round"],
    color: "#ff9500",
    description: "Classic sweet carrots rich in beta-carotene",
    isActive: true,
  },
  {
    name: "Purple Carrot",
    ingredientType: "vegetable" as const,
    baseIngredient: "carrot",
    variantName: "Purple",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.14",
    currentMarketPrice: "0.14",
    seasonalAvailability: ["fall", "winter", "spring"],
    color: "#663399",
    description: "Heirloom variety with earthy, slightly spicy flavor",
    isActive: true,
  },
  {
    name: "Baby Carrot",
    ingredientType: "vegetable" as const,
    baseIngredient: "carrot",
    variantName: "Baby",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.11",
    currentMarketPrice: "0.11",
    seasonalAvailability: ["year-round"],
    color: "#ffa500",
    description: "Tender young carrots with concentrated sweetness",
    isActive: true,
  },

  // Beets
  {
    name: "Red Beet",
    ingredientType: "vegetable" as const,
    baseIngredient: "beet",
    variantName: "Red",
    origin: "Wisconsin",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.13",
    currentMarketPrice: "0.13",
    seasonalAvailability: ["fall", "winter"],
    color: "#8b0000",
    description: "Deep earthy flavor with natural sweetness",
    isActive: true,
  },
  {
    name: "Golden Beet",
    ingredientType: "vegetable" as const,
    baseIngredient: "beet",
    variantName: "Golden",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.15",
    currentMarketPrice: "0.15",
    seasonalAvailability: ["fall", "winter"],
    color: "#ffd700",
    description: "Milder, sweeter than red beets with beautiful color",
    isActive: true,
  },

  // Greens
  {
    name: "Lacinato Kale",
    ingredientType: "vegetable" as const,
    baseIngredient: "kale",
    variantName: "Lacinato",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.17",
    currentMarketPrice: "0.17",
    seasonalAvailability: ["fall", "winter", "spring"],
    color: "#2d5016",
    description: "Tender dinosaur kale with sweet, earthy flavor",
    isActive: true,
  },
  {
    name: "Curly Kale",
    ingredientType: "vegetable" as const,
    baseIngredient: "kale",
    variantName: "Curly",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.15",
    currentMarketPrice: "0.15",
    seasonalAvailability: ["year-round"],
    color: "#355e3b",
    description: "Classic kale with robust, peppery flavor",
    isActive: true,
  },
  {
    name: "Baby Spinach",
    ingredientType: "vegetable" as const,
    baseIngredient: "spinach",
    variantName: "Baby",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.19",
    currentMarketPrice: "0.19",
    seasonalAvailability: ["year-round"],
    color: "#3f704d",
    description: "Tender young leaves with mild, sweet flavor",
    isActive: true,
  },
  {
    name: "Mature Spinach",
    ingredientType: "vegetable" as const,
    baseIngredient: "spinach",
    variantName: "Mature",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.16",
    currentMarketPrice: "0.16",
    seasonalAvailability: ["year-round"],
    color: "#2d5016",
    description: "Full-flavored leaves packed with iron",
    isActive: true,
  },

  // Other Vegetables
  {
    name: "Celery",
    ingredientType: "vegetable" as const,
    baseIngredient: "celery",
    variantName: "Organic",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.11",
    currentMarketPrice: "0.11",
    seasonalAvailability: ["year-round"],
    color: "#9acd32",
    description: "Crisp stalks with refreshing, slightly salty taste",
    isActive: true,
  },
  {
    name: "Cucumber",
    ingredientType: "vegetable" as const,
    baseIngredient: "cucumber",
    variantName: "English",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.10",
    currentMarketPrice: "0.10",
    seasonalAvailability: ["summer"],
    color: "#90ee90",
    description: "Mild, hydrating vegetable with clean taste",
    isActive: true,
  },
  {
    name: "Tomato",
    ingredientType: "vegetable" as const,
    baseIngredient: "tomato",
    variantName: "Heirloom",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.21",
    currentMarketPrice: "0.21",
    seasonalAvailability: ["summer"],
    color: "#ff6347",
    description: "Rich, complex flavor with balanced acidity",
    isActive: true,
  },
  {
    name: "Bell Pepper",
    ingredientType: "vegetable" as const,
    baseIngredient: "bell pepper",
    variantName: "Red",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.18",
    currentMarketPrice: "0.18",
    seasonalAvailability: ["summer", "fall"],
    color: "#e63946",
    description: "Sweet peppers at peak ripeness",
    isActive: true,
  },

  // ========== HERBS ==========
  {
    name: "Peppermint",
    ingredientType: "herb" as const,
    baseIngredient: "mint",
    variantName: "Peppermint",
    origin: "Oregon",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.32",
    currentMarketPrice: "0.32",
    seasonalAvailability: ["summer"],
    color: "#98ff98",
    description: "Cooling mint with menthol notes",
    isActive: true,
  },
  {
    name: "Spearmint",
    ingredientType: "herb" as const,
    baseIngredient: "mint",
    variantName: "Spearmint",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.28",
    currentMarketPrice: "0.28",
    seasonalAvailability: ["spring", "summer"],
    color: "#00fa9a",
    description: "Sweet, refreshing mint with subtle flavor",
    isActive: true,
  },
  {
    name: "Sweet Basil",
    ingredientType: "herb" as const,
    baseIngredient: "basil",
    variantName: "Sweet",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.35",
    currentMarketPrice: "0.35",
    seasonalAvailability: ["summer"],
    color: "#50c878",
    description: "Aromatic herb with anise-like notes",
    isActive: true,
  },
  {
    name: "Fresh Ginger Root",
    ingredientType: "herb" as const,
    baseIngredient: "ginger",
    variantName: "Fresh Root",
    origin: "Hawaii",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.38",
    currentMarketPrice: "0.38",
    seasonalAvailability: ["year-round"],
    color: "#f4e4c1",
    description: "Spicy, warming root with digestive benefits",
    isActive: true,
  },
  {
    name: "Fresh Turmeric Root",
    ingredientType: "herb" as const,
    baseIngredient: "turmeric",
    variantName: "Fresh Root",
    origin: "Hawaii",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.42",
    currentMarketPrice: "0.42",
    seasonalAvailability: ["year-round"],
    color: "#ffb347",
    description: "Golden root with anti-inflammatory properties",
    isActive: true,
  },
  {
    name: "Cilantro",
    ingredientType: "herb" as const,
    baseIngredient: "cilantro",
    variantName: "Fresh",
    origin: "California",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.25",
    currentMarketPrice: "0.25",
    seasonalAvailability: ["spring", "summer", "fall"],
    color: "#7cb342",
    description: "Bright, citrusy herb for detoxification",
    isActive: true,
  },
  {
    name: "Parsley",
    ingredientType: "herb" as const,
    baseIngredient: "parsley",
    variantName: "Italian",
    origin: "Michigan",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.22",
    currentMarketPrice: "0.22",
    seasonalAvailability: ["year-round"],
    color: "#4caf50",
    description: "Fresh, slightly peppery herb rich in vitamins",
    isActive: true,
  },

  // ========== PREMIUM SUPPLEMENTS ==========
  {
    name: "Chia Seeds",
    ingredientType: "supplement" as const,
    baseIngredient: "chia",
    variantName: "Black Chia",
    origin: "Mexico",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.48",
    currentMarketPrice: "0.48",
    seasonalAvailability: ["year-round"],
    color: "#2b2b2b",
    description: "Omega-3 rich seeds that create gel-like texture",
    isActive: true,
  },
  {
    name: "Cayenne Pepper",
    ingredientType: "supplement" as const,
    baseIngredient: "cayenne",
    variantName: "Ground",
    origin: "India",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.55",
    currentMarketPrice: "0.55",
    seasonalAvailability: ["year-round"],
    color: "#a6001a",
    description: "Spicy pepper to boost metabolism",
    isActive: true,
  },
  {
    name: "Raw Honey",
    ingredientType: "supplement" as const,
    baseIngredient: "honey",
    variantName: "Raw Wildflower",
    origin: "Illinois",
    isOrganic: false,
    isLocalChicago: true,
    baseCostPerOz: "0.65",
    currentMarketPrice: "0.65",
    seasonalAvailability: ["year-round"],
    color: "#f0c420",
    description: "Unfiltered honey with natural enzymes",
    isActive: true,
  },
  {
    name: "Manuka Honey",
    ingredientType: "supplement" as const,
    baseIngredient: "honey",
    variantName: "Manuka UMF 15+",
    origin: "New Zealand",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "1.85",
    currentMarketPrice: "1.85",
    seasonalAvailability: ["year-round"],
    color: "#daa520",
    description: "Premium medicinal honey with antibacterial properties",
    isActive: true,
  },
  {
    name: "Spirulina",
    ingredientType: "supplement" as const,
    baseIngredient: "spirulina",
    variantName: "Blue-Green Algae",
    origin: "Hawaii",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.95",
    currentMarketPrice: "0.95",
    seasonalAvailability: ["year-round"],
    color: "#006d5b",
    description: "Nutrient-dense superfood with complete protein",
    isActive: true,
  },
  {
    name: "Chlorella",
    ingredientType: "supplement" as const,
    baseIngredient: "chlorella",
    variantName: "Broken Cell Wall",
    origin: "Japan",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.88",
    currentMarketPrice: "0.88",
    seasonalAvailability: ["year-round"],
    color: "#2d5f3f",
    description: "Detoxifying green algae with high chlorophyll",
    isActive: true,
  },
  {
    name: "Wheatgrass",
    ingredientType: "supplement" as const,
    baseIngredient: "wheatgrass",
    variantName: "Fresh Juice",
    origin: "Illinois",
    isOrganic: true,
    isLocalChicago: true,
    baseCostPerOz: "0.72",
    currentMarketPrice: "0.72",
    seasonalAvailability: ["year-round"],
    color: "#6b8e23",
    description: "Alkalizing grass juice packed with enzymes",
    isActive: true,
  },
  {
    name: "Activated Charcoal",
    ingredientType: "supplement" as const,
    baseIngredient: "charcoal",
    variantName: "Coconut Activated",
    origin: "Philippines",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.78",
    currentMarketPrice: "0.78",
    seasonalAvailability: ["year-round"],
    color: "#1c1c1c",
    description: "Detoxifying charcoal from coconut shells",
    isActive: true,
  },
  {
    name: "Cacao Powder",
    ingredientType: "supplement" as const,
    baseIngredient: "cacao",
    variantName: "Raw",
    origin: "Ecuador",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "0.58",
    currentMarketPrice: "0.58",
    seasonalAvailability: ["year-round"],
    color: "#3e2723",
    description: "Raw chocolate powder rich in antioxidants",
    isActive: true,
  },
  {
    name: "Matcha Powder",
    ingredientType: "supplement" as const,
    baseIngredient: "matcha",
    variantName: "Ceremonial Grade",
    origin: "Japan",
    isOrganic: true,
    isLocalChicago: false,
    baseCostPerOz: "1.25",
    currentMarketPrice: "1.25",
    seasonalAvailability: ["year-round"],
    color: "#7cb518",
    description: "Premium stone-ground green tea with L-theanine",
    isActive: true,
  },
];

// Seed function
export async function seedIngredients() {
  console.log("Seeding ingredient variants...");

  try {
    // Clear existing ingredients first
    console.log("Clearing existing ingredient variants...");
    await db.delete(ingredientVariants);
    console.log("✓ Cleared existing ingredients");

    // Insert all ingredients
    const inserted = await db.insert(ingredientVariants).values(ingredientSeedData).returning();
    console.log(`✓ Seeded ${inserted.length} ingredient variants`);
    return inserted;
  } catch (error) {
    console.error("Error seeding ingredients:", error);
    throw error;
  }
}
